export default [
    {
        id: 'apple',
        title: 'apple',
        product: [
            {
                id: 1,
                title: 'Shinji Ikari Case',
                price: '89,000',
                img: '../images/colab/Shinji_Ikari_Case_1.webp',
                type: 'apple',
                series: 'mirror',
            },
            {
                id: 2,
                title: 'Rei Ayanami Case',
                price: '89,000',
                img: '../images/colab/Rei_Ayanami_Case_1.webp',
                type: 'apple',
                series: 'mirror',
            },
            {
                id: 3,
                title: 'Asuka Shikinami Langley Case',
                price: '89,000',
                img: '../images/colab/Asuka_Shikinami_Langley_Case.webp',
                type: 'apple',
                series: 'mirror',
            },
            {
                id: 4,
                title: 'Kaworu Nagisa Case',
                price: '89,000',
                img: '../images/colab/Kaworu_Nagisa_Case.webp',
                type: 'apple',
                series: 'mirror',
            },
            {
                id: 5,
                title: 'NERV Logo Case',
                price: '89,000',
                img: '../images/colab/NERV_Logo_Case.webp',
                type: 'apple',
                series: 'mirror',
            },
            {
                id: 6,
                title: 'NERV Watch Band',
                price: '64,000',
                img: '../images/colab/NERV_Watch_Band.webp',
                type: 'acc',
                series: 'impact',
            },
            {
                id: 7,
                title: 'Evangelion Proto Type Unit-00',
                price: '77,000',
                img: '../images/colab/Evangelion_Proto_Type_Unit-00_Case.webp',
                type: 'apple',
                series: 'impact',
            },
            {
                id: 8,
                title: 'Evangelion Mark.06 Case',
                price: '89,000',
                img: '../images/colab/Evangelion Mark.06 Case89000.webp',
                type: 'samsung',
                series: 'impact',
            },
            {
                id: 9,
                title: 'Sounds Only Case 04',
                price: '91,000',
                img: '../images/colab/Sounds_Only_Case_04.webp',
                type: 'apple',
                series: 'impact',
            },
            {
                id: 10,
                title: 'SEELE Logo Case',
                price: '89,000',
                img: '../images/colab/SEELE_Logo_Case .webp',
                type: 'apple',
                series: 'mirror',
            },
            {
                id: 11,
                title: 'Evangelion Test Type-01',
                price: '102,000',
                img: '../images/colab/Evangelion_Test_Type-01_Case.webp',
                type: 'apple',
                series: 'bounce',
            },
            {
                id: 12,
                title: 'Shinji Ikari Watch Band',
                price: '64,000',
                img: '../images/colab/Shinji_Ikari_Watch_Band .webp',
                type: 'acc',
                series: 'impact',
            },
            {
                id: 13,
                title: 'Angel MagSafe Wallet',
                price: '58,000',
                img: '../images/colab/Angel MagSafe Wallet58000.webp',
                type: 'acc',
                series: '',
            },
            {
                id: 14,
                title: 'NERV Logo Magnetic Wireless Charger',
                price: '51,000',
                img: '../images/colab/NERV Logo Magnetic Wireless Charger51000.webp',
                type: 'acc',
                series: '',
            },
            {
                id: 15,
                title: 'Evangelion Production Model -08 Case',
                price: '102,000',
                img: '../images/colab/Evangelion Production Model -08 Case102000.webp',
                type: 'samsung',
                series: 'ring',
            },
            {
                id: 16,
                title: 'NERV Logo Snappy Grip Stand',
                price: '45,000',
                img: '../images/colab/NERV Logo Snappy Grip Stand45000.webp',
                type: 'apple',
                series: '',
            },
        ],
    },
];
